// Code generated by "stringer -type=Class"; DO NOT EDIT.

package cataRando

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Druid-0]
	_ = x[Hunter-1]
	_ = x[Mage-2]
	_ = x[Paladin-3]
	_ = x[Priest-4]
	_ = x[Rogue-5]
	_ = x[Shaman-6]
	_ = x[Warlock-7]
	_ = x[Warrior-8]
}

const _Class_name = "DruidHunterMagePaladinPriestRogueShamanWarlockWarrior"

var _Class_index = [...]uint8{0, 5, 11, 15, 22, 28, 33, 39, 46, 53}

func (i Class) String() string {
	if i < 0 || i >= Class(len(_Class_index)-1) {
		return "Class(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Class_name[_Class_index[i]:_Class_index[i+1]]
}
